//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string First_answer { get; set; }
        public string Second_answer { get; set; }
        public string Third_answer { get; set; }
        public int ID_test { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
